### ISSUE TITLE
Invalid JSON

### ISSUE THREAD

**Issue by mdgreenwald** [nicolewhite/simplebank#1]
Hi, attempting to create a goal results in this:

```
Traceback (most recent call last):
  File "goals.py", line 5, in <module>
    goals = simple.goals()
  File "/Library/Python/2.7/site-packages/simplebank-0.0.1-py2.7.egg/simplebank/__init__.py", line 89, in goals
    goals = goals.json()
  File "/Library/Python/2.7/site-packages/requests-2.12.1-py2.7.egg/requests/models.py", line 841, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Python/2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/Library/Python/2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/Library/Python/2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 3 column 1 (char 2)
```

I suspect this may be due to 2FA being enabled by default now.

**Comment by ethanroy** [comment]
@nicolewhite What do you think about adding support for 2FA?

Maybe a method to submit the login, which would cause the code to get sent back to the user, and another method to submit the 2FA code to complete authentication.

Let me know what you think, I'd be willing to help and submit a PR!

**Comment by mdgreenwald** [comment]
@ethanroy Ethan, do you have something working that can achieve this?

**Comment by nicolewhite** [comment]
Hey guys, would love to take a look at this. Someone else emailed me about it as well. I will try to get it working when I find some time, but feel free to open a PR if you've figured it out.

**Comment by gageorsburn** [comment]
I think I almost have this working, it's trickier than what @ethanroy mentioned above. I'm currently locked out of my account due to too many attempts but I'll post the logic when I get it.

**Comment by gageorsburn** [comment]
The rough logic (I probably should split this out into methods but it works):
```
 90 class Simple:
 91     def __init__(self, *args, **kwargs):
 92         self.session = requests.Session()
 93         self.session.headers = {"User-Agent": "Mozilla/5.0"}
 94
 95         self.baseUrl = "https://bank.simple.com"
 96         self.signInUrl = "https://signin.simple.com"
 97
 98         response = self.session.get(self.signInUrl)
 99         self.csrf = re.search('<meta name="_csrf" content="(.*)">', response.text).group(1)
100
101         payload = {
102             "username":  kwargs.get("username"),
103             "password": kwargs.get("password"),
104             "_csrf": self.csrf
105         }
106
107         response = self.session.post(self.signInUrl, data=payload)
108
109         too_many_attempts = re.search('Too many attempts, try again later.', response.text)
110
111         if too_many_attempts:
112             raise Exception("Too many attempts. Fuck.")
113
114         self.partial_auth_token = re.search('<input type="hidden" value="(.*)" name="partial_auth_token" class="optional">', response.text).group(1)
115
116         pin = input("What is the pin? ")
117
118         payload = {
119             "_csrf": self.csrf,
120             "partial_auth_token": self.partial_auth_token,
121             "pin": pin
122         }
123
124         response = self.session.post("{}/verify".format(self.signInUrl), data=payload)
125         response = self.session.get(self.baseUrl)
126
127         self.user_id = re.search('data-uuid="(.*)"', response.text).group(1)
128         self.account_id = re.search('data-account-reference="(.*)"', response.text).group(1)
```
Note that I don't know how to programmatically get the token that gets sent as a text message. At least with a regular phone provider. It is 100% possible though to set up a twilio account and make a request to them to get the token.

user_id and account_id are useful because it looks like there's an api that returns json data.

```
133         url = "{}/goals-api/users/{}/accounts/{}/goals".format(self.baseUrl, self.user_id, self.account_id)
134         response = self.session.get(url)
```

**Comment by 11jwolfe2** [comment]
Was this ever resolved?
